# Generated by Django 4.2.1 on 2023-05-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_groups'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='city',
            field=models.CharField(default='t', max_length=200, verbose_name='Город'),
        ),
    ]
